import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: { absolute: 'Privacy Policy — Mlytics' },
  description: 'Read the Mlytics Privacy & Security Policy to understand how we collect, use, and protect your personal information.',
  alternates: { canonical: '/privacy-policy/' },
}

export default function PrivacyPolicyPage() {
  return (
    <>
      <div className="section-dark pt-32 pb-12 text-center" style={{ borderBottom: '1px solid rgba(168,197,195,0.12)' }}>
        <div className="max-w-3xl mx-auto px-6">
          <span className="inline-block text-xs font-semibold uppercase tracking-widest mb-4 px-3 py-1.5 rounded-full" style={{ background: 'rgba(34,93,89,0.4)', color: 'var(--color-on-dark)', border: '1px solid rgba(34,93,89,0.6)' }}>Privacy Policy</span>
          <h1 className="text-4xl md:text-5xl font-bold text-white leading-tight mb-4">Mlytics</h1>
          <p className="text-base max-w-xl mx-auto" style={{ color: 'var(--color-on-dark)' }}>Learn about Mlytics Privacy Policy</p>
        </div>
      </div>

      <section className="section-white py-16 lg:py-20">
        <div className="max-w-3xl mx-auto px-6">

          <div className="mb-10">
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>This Mlytics Privacy &amp; Security Policy (&quot;Policy&quot;) outlines the general policy and practices for the types of information that Mlytics, Inc. (&quot;Mlytics&quot;, &quot;we&quot;, &quot;us&quot; or &quot;our&quot;) gathers, how we use that information, and the options that our users (&quot;you&quot; or &quot;your&quot;) have regarding our use of, and your ability to correct, such information.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>It&apos;s our overriding privacy principle that any personal information provided to us by you is just that: personal and private. As such, we will never sell, rent, share, or otherwise disclose your personal information to anyone except to provide our services or as otherwise described in this Policy, without providing explicit notice of such and the ability to opt-out.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>Mlytics&apos;s website and services are not intended for, nor designed to attract, individuals under the age of eighteen. Mlytics does not knowingly collect personally identifiable information from any person under the age of eighteen.</p>
            <p className="text-sm leading-relaxed mb-3 font-semibold" style={{ color: 'var(--color-ink)' }}>APPLICABILITY</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>This Policy applies to information provided to us by: (i) visitors to our websites, (ii) users of our services (i.e., subscribers to any of our plans), and (iii) information we collect from visitors to the websites of our users. We generally serve merely as a conduit for information controlled by others, and as such this Policy may not apply to our users&apos; websites. Our users&apos; websites or those to which we provide links, may have their own privacy policies. Because of this, we strongly encourage awareness and understanding of such websites&apos; separate privacy policies.</p>
            <p className="text-sm leading-relaxed mb-3 font-semibold" style={{ color: 'var(--color-ink)' }}>INFORMATION COLLECTION AND SHARING</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>Mlytics is the owner of the service information collected on this website and through any Mlytics service. Mlytics collects information automatically about visits to our Websites, including portals for customers who use our services (&quot;Portals&quot;). Such information may include, for example, the browser used, referring site, and the time and date of each web request. We collect this information to understand how visitors use our Websites. We also collect traffic data, like IP addresses and cookie data and other tracking information. We also collect information you provide to us, such as your name, title, company, email address and phone number, when you contact us using the contact information or forms included on our Websites.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>Other third parties who provide us with services may also collect the information described above about your online activities over time and across different Web sites when you visit our Websites.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>As part of our services, we may build statistical reports based upon what malicious visitors have visited certain site(s), in order to further protect your sites. We may also share information about our users or their visitors where we have a reasonable belief that they pose a security threat.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>In order for us to provide some of our services we may also provide information that you supply to us to our affiliates, vendors and service providers, which we use for billing systems, contract and account management, customer support, relationship management and other technical operations. In such cases, we will ensure that such entities are bound by appropriate confidentiality restrictions to protect the information covered by this Policy. However, we will never use or share personal information that you provide to us in ways.</p>
            <p className="text-sm leading-relaxed mb-3 font-semibold" style={{ color: 'var(--color-ink)' }}>BILLING INFORMATION</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>Mlytics collects and maintains certain information from our users for the purposes of billing. We may share this information with third party processors for the limited purpose of receiving payment. We do not store full credit card numbers or personal account numbers (PANs).</p>
            <p className="text-sm leading-relaxed mb-3 font-semibold" style={{ color: 'var(--color-ink)' }}>COOKIES</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>Our site and services use &quot;cookies&quot; in order to provide a better service to you. Cookies are placed by a browser onto your computer&apos;s hard drive to assign a unique identification to that computer. For example, we may use cookies to help direct you to the appropriate part of our website, by indicating that you are a repeat visitor to our website. We may also use information provided to us to present you with services that are customized to your preferences. Mlytics does not store information we consider personal or private in a cookie, unless that information is obscured.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>Some portions of our website are functional without cookies. You may delete Mlytics&apos;s cookies yourself through your browser&apos;s cookie manager. However, disabling cookies will reset your session, disable auto-login, and may adversely affect other functions on the Mlytics website and the services we provide.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>As part of our services, we may place cookies on the computers of visitors to Mlytics protected websites. We do this in order to identify malicious visitors, reduce the chance of blocking legitimate users, and to provide customized services.</p>
            <p className="text-sm leading-relaxed mb-3 font-semibold" style={{ color: 'var(--color-ink)' }}>PROTECTION OF PERSONALLY IDENTIFYING INFORMATION</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>Mlytics undertake reasonable security measures to protect data to guard against unauthorized access to personal data. If you use our Portal, you are responsible for safeguarding your username and password. For Customer Services, Mlytics&apos; security practices are governed by its agreements with its customers and partners.</p>
            <p className="text-sm leading-relaxed mb-3 font-semibold" style={{ color: 'var(--color-ink)' }}>LAW ENFORCEMENT AND OBLIGATIONS</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>It&apos;s possible that we may be required by law, court order, or other legal process to provide information about our customers to outside parties. It&apos;s our policy to ensure adherence to the due process of law in all such instances, and if we are required to provide information under these circumstances, we will, whenever possible, attempt to inform users whose information we are compelled to produce, unless prohibited by law.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>We may also retain copies of personal information to comply with our legal obligations, pursuant to our data retention policies, or for such reasonable period as is required to address potential disputes.</p>
            <p className="text-sm leading-relaxed mb-3 font-semibold" style={{ color: 'var(--color-ink)' }}>DATA SECURITY, DATA INTEGRITY, AND ACCESS</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>We take all reasonable steps to protect information we receive from our users from loss, misuse or unauthorized access, disclosure, alteration and/or destruction. We&apos;ve put in place appropriate physical, electronic and managerial procedures to safeguard and secure such information. Mlytics only processes personal information in a way that is compatible with and relevant for the purpose for which it was collected or authorized. We allow our users and their website visitors access to their own personal information, and allow them to correct, amend, or delete inaccurate personal information, except where the burden or expense of providing such access is disproportionate to the individual privacy risk, or where the rights of persons other than the requesting individual risk being violated.</p>
            <p className="text-sm leading-relaxed mb-3 font-semibold" style={{ color: 'var(--color-ink)' }}>REGISTRAR</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>If you purchase Mlytics&apos;s registrar service, ICANN and the registry operators overseeing a domain&apos;s TLD require us to publish registrant data via the &quot;WHOIS&quot; protocol. We may also be required to share this public data with ICANN, registry operators, and other such bodies. Registrant data includes domain name, registrant name and contact information, and domain nameserver information.</p>
            <p className="text-sm leading-relaxed mb-3 font-semibold" style={{ color: 'var(--color-ink)' }}>INTERNATIONAL DATA TRANSFERS</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>Mlytics is certified under both the EU-U.S. Privacy Shield Framework, and the Swiss-U.S. Privacy Shield Framework, each as set forth by the U.S. Department of Commerce regarding the collection, use, and retention of personal data transferred from the European Economic Area and Switzerland to the United States, respectively. A detailed description of how we comply with the Privacy Shield Principles can be found here. For more information on the EU-U.S. Privacy Shield or Swiss-U.S. Privacy Shield, please visit the U.S. Department of Commerce&apos;s Privacy Shield website at: https://www.privacyshield.gov/welcome.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>ACCESSING OR USING OUR SITES OR SERVICES, OR OTHERWISE PROVIDING INFORMATION TO US OR OUR CUSTOMERS, CONSTITUTES CONSENTING TO OUR POTENTIAL TRANSFER, PROCESSING, AND STORAGE OF SUCH INFORMATION IN THE UNITED STATES.</p>
            <p className="text-sm leading-relaxed mb-3 font-semibold" style={{ color: 'var(--color-ink)' }}>IINFORMATION SECURITY POLICY</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>This security policy shall serve as a basis to be followed in abiding by related regulations and in safeguarding the information assets of Mlytics (information assets include but not restricted to information, software, and hardware facility) against risk from being tampered, exposed, destroyed, or lost due to external threat or mismanagement and misuse of internal staff.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>This Information Security Policy (hereinafter referred to as the Policy) drawn up based on the mission and objective of Mlytics and in accordance with related laws and regulations.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: 'var(--color-ink)' }}>1. The Essence Of Information Security</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>The essence of information security is roughly classified as follows:</p>
            <p className="text-sm leading-relaxed mb-2" style={{ color: 'var(--color-ink-muted)' }}>1. Availability – To Ensure That Various Information Assets Are Provided Instantly And Accurately In Order To Meet Users&apos; Needs.</p>
            <p className="text-sm leading-relaxed mb-2" style={{ color: 'var(--color-ink-muted)' }}>2. Integrity – Information Assets Are Classified According To Their Importance And Safeguarded Appropriately To Ensure The Integrity Of Information Assets.</p>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--color-ink-muted)' }}>3. Confidentiality – Proper Grading Of Data Confidentiality And Be Given A Proper Standard And Protection According To The Grade Of Confidentiality. The Information Security Of Mlytics Is To Ensure The Integrity, Availability, And Confidentiality Of All The Information Assets Of Mlytics.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: 'var(--color-ink)' }}>2. Purpose Of Policy And Description</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--color-ink-muted)' }}>In order to achieve the mission and objective of Mlytics, to meet the expectation and requirement of the highest management level on information security, and to ensure that all the information assets of Mlytics is secured, the purpose of drawing up the information security policy of Mlytics is as follows:</p>
            <p className="text-sm leading-relaxed mb-2" style={{ color: 'var(--color-ink-muted)' }}>1. To Ensure The Confidentiality Of The Relevant Business Information Of Mlytics, Prevent The Sensitive Data Of The Agency And Personal Data Of The People From Leaking And Get Lost.</p>
            <p className="text-sm leading-relaxed mb-2" style={{ color: 'var(--color-ink-muted)' }}>2. To Ensure The Integrity And Availability Of Relevant Business Information Of Mlytics, In Order To Carryout The Work Of Mlytics And Its Various Businesses.</p>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--color-ink-muted)' }}>3. An Integrated, Feasible, And Effective Information Security Management System (Hereinafter Referred To As Isms) Was Created By The Policy Based On The Necessity Of Organizational Development And By Taking Information Asset Risk Into Account, In Which Asset Risk Underwent Systemized Risk Evaluation, Handled, And Managed In Accordance With The Evaluation Result, And A Written Procedure Was Also Created For Various Plans, Operation, And Control Process Of Information Security, In Order To Provide Optimum Assurance To The Information Security Of The Mlytics. The Information Policy Is Evaluated At Least Once A Year In Order To Keep Up With The Changes Of The Law And The Development Of Technology And Related Business. Thus, The Effectiveness Of Information Security Is Guaranteed.</p>
          </div>

        </div>
      </section>
    </>
  )
}
