import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: { absolute: 'Terms of Service — Mlytics' },
  description: 'Read the Mlytics Master Subscription Terms governing the use of our services.',
  alternates: { canonical: '/terms-of-service/' },
}

export default function TermsOfServicePage() {
  return (
    <>
      <div className="section-dark pt-32 pb-12 text-center" style={{ borderBottom: '1px solid rgba(168,197,195,0.12)' }}>
        <div className="max-w-3xl mx-auto px-6">
          <span className="inline-block text-xs font-semibold uppercase tracking-widest mb-4 px-3 py-1.5 rounded-full" style={{ background: 'rgba(34,93,89,0.4)', color: '#A8C5C3', border: '1px solid rgba(34,93,89,0.6)' }}>Terms of Service</span>
          <h1 className="text-4xl md:text-5xl font-bold text-white leading-tight mb-4">Mlytics</h1>
          <p className="text-base max-w-xl mx-auto" style={{ color: '#A8C5C3' }}>Mlytics Master Subscriptions Terms</p>
        </div>
      </div>

      <section className="section-white py-16 lg:py-20">
        <div className="max-w-3xl mx-auto px-6">

          <div className="mb-10">
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>It&apos;s our overriding privacy principle that any personal information provided to us by you is just that: personal and private. As such, we will never sell, rent, share, or otherwise disclose your personal information to anyone except to provide our services or as otherwise described in this Policy, without providing explicit notice of such and the ability to opt-out.</p>
            <p className="text-sm leading-relaxed" style={{ color: '#4A4A4A' }}>Mlytics&apos;s website and services are not intended for, nor designed to attract, individuals under the age of eighteen. Mlytics does not knowingly collect personally identifiable information from any person under the age of eighteen.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1A1A1A' }}>1. Provision Of Subscription</h2>
            <p className="text-sm leading-relaxed" style={{ color: '#4A4A4A' }}>Subject to the terms of this Agreement, Mlytics will use commercially reasonable efforts to provide Client the Services. Unless otherwise provided in the applicable Order Form, Services are purchased as a subscription. Mlytics hereby grants Client a non-exclusive, non-sublicenseable, nontransferable right to access and use the Services during the Subscription Term, solely for Client&apos;s internal business purposes. Mlytics and its licensors reserve all rights to the Services not expressly granted in this Agreement. Mlytics reserves the right to create and maintain administrative, support, system, and maintenance accounts within the Service, all with the necessary data access for Mlytics and its assigned operators and/or other service providers to deliver the Service.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1A1A1A' }}>2. Restrictions And Responsibilities</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>Client will not (i) sublicense, sell, transfer, assign, distribute or otherwise commercially exploit the Service; (ii) modify or create derivative works based on the Service (iii) create Internet &quot;links&quot; to the Service or &quot;frame&quot; or &quot;mirror&quot; any content provided in connection therewith; or (iv) reverse engineer, access or use the Service to build a product using ideas, features, functions or graphics similar to the Service, or (iii) copy any ideas, features, functions or graphics of the Service. Client will not use the Service to interfere with or disrupt the integrity or performance of the Service or the data contained therein. Client will not attempt to gain unauthorized access to the Service or its related systems or networks. Client will not provide or disclose to, or permit use of the Services by, persons other than Client&apos;s employees and contractors who are under a legally binding obligation of confidentiality consistent with this Agreement. Mlytics reserves the right to suspend and/or terminate this Agreement and the applicable access rights in the event of any breach of this Section. Such suspension and/or termination will be without prejudice as to Mlytics&apos; other rights and remedies, and without penalty for Mlytics or liability to Client.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>Client represents, covenants, and warrants that Client will use the Services only in compliance with Mlytics&apos;s standard published policies then in effect (the &quot;Policy&quot;) and all applicable laws and regulations. Client hereby agrees to indemnify and hold harmless Mlytics against any damages, losses, liabilities, settlements and expenses (including without limitation costs and attorneys&apos; fees) in connection with any claim or action that arises from an alleged violation of the foregoing or otherwise from Client&apos;s use of Services. Although Mlytics has no obligation to monitor Client&apos;s use of the Services, Mlytics may do so and may prohibit any use of the Services it believes may be (or alleged to be) in violation of the foregoing.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>Client shall be responsible for obtaining and maintaining any equipment and ancillary services needed to connect to, access or otherwise use the Services, including, without limitation, modems, hardware, servers, software, operating systems, networking, web servers and the like (collectively, &quot;Equipment&quot;). Client shall also be responsible for maintaining the security of the Equipment, Client account, passwords (including but not limited to administrative and user passwords) and files, and for all uses of Client account or the Equipment with or without Client&apos;s knowledge or consent.</p>
            <p className="text-sm leading-relaxed" style={{ color: '#4A4A4A' }}>Client may grant Affiliate(s) access the Services, provided that any act or omission by an Affiliate in breach of this Agreement will be deemed a breach by Client. Further, Client&apos;s Affiliates may purchase Services under the terms of this Agreement by executing an Order Form that specifically references the terms of this Agreement.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1A1A1A' }}>3. Usage Limits</h2>
            <p className="text-sm leading-relaxed" style={{ color: '#4A4A4A' }}>Services are subject to usage limits, including, for example, the quantities of decisions listed in an Order Form. If Client exceeds a contractual usage limit, Client agrees to be invoiced for additional usage at Mlytics&apos; then current list price or at the applicable pricing referenced in the corresponding Order Form.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1A1A1A' }}>4. Confidentiality; Proprietary Rights</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>Each party (the &quot;Receiving Party&quot;) understands that the other party (the &quot;Disclosing Party&quot;) has disclosed or may disclose business, technical or financial information relating to the Disclosing Party&apos;s business (hereinafter referred to as &quot;Proprietary Information&quot; of the Disclosing Party). Proprietary Information of Mlytics includes non-public information regarding features, functionality and performance of the Service. Proprietary Information of Client includes non-public data provided by Client to Mlytics to enable the provision of the Services (&quot;Client Data&quot;). The Receiving Party agrees: (i) to take reasonable precautions to protect such Proprietary Information, and (ii) not to use (except in performance of the Services or as otherwise permitted herein) or divulge to any third person any such Proprietary Information. The Disclosing Party agrees that the foregoing shall not apply with respect to any information after five (5) years following the disclosure thereof or any information that the Receiving Party can document (a) is or becomes generally available to the public, or (b) was in its possession or known by it prior to receipt from the Disclosing Party, or (c) was rightfully disclosed to it without restriction by a third party, or (d) was independently developed without use of any Proprietary Information of the Disclosing Party or (e) is required to be disclosed by law.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>Client shall own all right, title and interest in and to the Client Data. Mlytics shall own and retain all right, title and interest in and to (a) the Services and Software, all improvements, enhancements or modifications thereto, (b) any software, applications, inventions or other technology developed in connection with Implementation Services or support, and (c) all intellectual property rights related to any of the foregoing.</p>
            <p className="text-sm leading-relaxed" style={{ color: '#4A4A4A' }}>Notwithstanding anything to the contrary, Mlytics shall have the right collect and analyze data and other information relating to the provision, use and performance of various aspects of the Services and related systems and technologies (including, without limitation, information concerning Client Data and data derived therefrom), and Mlytics will be free (during and after the term hereof) to (i) use such information and data to improve and enhance the Services and for other development, diagnostic and corrective purposes in connection with the Services and other Mlytics offerings, and (ii) disclose such data solely in aggregate or other de-identified form in connection with its business. No rights or licenses are granted except as expressly set forth herein.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1A1A1A' }}>5. Fees And Payment Terms</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>Client will pay all invoices issued. Unless otherwise provided in the applicable Order Form, invoices will be issued upon commencement of the Subscription Term and additional periodic invoices may be issued for exceeded usage and renewals of the Subscription Term, in accordance with Section 3 above. Amounts are due and payable in full, without setoff or deduction, within thirty (30) days following the invoice date and are payable in U.S. dollars unless otherwise agreed. If Client reasonably disputes any invoiced amount in good faith, Client will notify Mlytics of such dispute in writing.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>The fees outlined in an Order Form will apply to both the initial term as well as any renewal terms. Fees may not be modified during the initial term. Mlytics reserves the right to modify its fees and charges upon at least thirty (30) days&apos; notice prior to any subsequent renewal Subscription Term; any fee adjustments will take effect upon the commencement of the subsequent Subscription Term.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>Mlytics may choose to bill through an invoice, in which case, full payment for invoices issued in any given month must be received by Mlytics thirty (30) days after the mailing date of the invoice. Unpaid amounts are subject to a finance charge of 1.5% per month on any outstanding balance, or the maximum permitted by law, whichever is lower, plus all expenses of collection and may result in immediate termination of Service.</p>
            <p className="text-sm leading-relaxed" style={{ color: '#4A4A4A' }}>Mlytics&apos; fees are exclusive of all taxes, levies, or duties, and Client will be responsible for payment of all such taxes, levies, or duties, excluding only United States (federal or state) taxes based solely on Mlytics&apos; income. Client will make all payments of fees to Mlytics free and clear of, and without reduction for, any VAT, withholding, or similar taxes; any such taxes imposed on payments of fees to Mlytics will be Client&apos;s sole responsibility, and Client will provide Mlytics with official receipts issued by the appropriate taxing authority, or such other evidence as Mlytics may reasonably request, to establish that such taxes have been paid. Client agrees to indemnify, defend, and hold Mlytics, its officers, directors, consultants, employees, successors and assigns harmless from all claims and liability arising from Client&apos;s failure to report or pay any such taxes, duties or assessments.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1A1A1A' }}>6. Term And Termination</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>Subject to earlier termination as provided below, this Agreement is for the Initial Service Term as specified in the Order Form, and shall be automatically renewed for additional periods of the same duration as the Initial Service Term (collectively, the &quot;Term&quot;), unless either party requests termination at least thirty (30) days prior to the end of the then-current term; provided, however, that the terms of this Agreement will continue to apply to any Order Forms that are still in effect.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>In addition to any other remedies it may have, either party may also terminate this Agreement upon thirty (30) days&apos; notice (or without notice in the case of nonpayment), if the other party materially breaches any of the terms or conditions of this Agreement. Client will pay in full for the Services up to and including the last day on which the Services are provided. All sections of this Agreement which by their nature should survive termination will survive termination, including, without limitation, accrued rights to payment, confidentiality obligations, warranty disclaimers, and limitations of liability.</p>
            <p className="text-sm leading-relaxed" style={{ color: '#4A4A4A' }}>Mlytics may immediately suspend or terminate this Agreement upon notice to Client that in Mlytics&apos; reasonable determination: (a) Client is in material breach of this Agreement (b) Client&apos;s use of the Services is interfering with, or could reasonably be expected to interfere with, Mlytics&apos; operation or provision of any third-party&apos;s use of the Services or any other business of Mlytics; or (c) the Client&apos;s use of the Services is harming, or could reasonably be expected to harm, Mlytics&apos; reputation; or (d) Client does not abide by all applicable laws, treaties and regulations in connection with use of the Service.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1A1A1A' }}>7. Warranty And Disclaimer</h2>
            <p className="text-sm leading-relaxed" style={{ color: '#4A4A4A' }}>Mlytics shall use reasonable efforts consistent with prevailing industry standards to maintain the Services in a manner which minimizes errors and interruptions in the Services and shall perform the Implementation Services in a professional and workmanlike manner. Services may be temporarily unavailable for scheduled maintenance or for unscheduled emergency maintenance, either by Mlytics or by third-party providers, or because of other causes beyond Mlytics&apos;s reasonable control, but Mlytics shall use reasonable efforts to provide advance notice in writing or by e-mail of any scheduled service disruption. HOWEVER, Mlytics DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR FREE; NOR DOES IT MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SERVICES. EXCEPT AS EXPRESSLY SET FORTH IN THIS SECTION, THE SERVICES AND IMPLEMENTATION SERVICES ARE PROVIDED &quot;AS IS&quot; AND Mlytics DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1A1A1A' }}>8. Limitation Of Liability</h2>
            <p className="text-sm leading-relaxed" style={{ color: '#4A4A4A' }}>NOTWITHSTANDING ANYTHING TO THE CONTRARY, EXCEPT FOR BODILY INJURY OF A PERSON, Mlytics AND ITS SUPPLIERS (INCLUDING BUT NOT LIMITED TO ALL EQUIPMENT AND TECHNOLOGY SUPPLIERS), OFFICERS, AFFILIATES, REPRESENTATIVES, CONTRACTORS AND EMPLOYEES SHALL NOT BE RESPONSIBLE OR LIABLE WITH RESPECT TO ANY SUBJECT MATTER OF THIS AGREEMENT OR TERMS AND CONDITIONS RELATED THERETO UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY: (A) FOR ERROR OR INTERRUPTION OF USE OR FOR LOSS OR INACCURACY OR CORRUPTION OF DATA OR COST OF PROCUREMENT OF SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY OR LOSS OF BUSINESS; (B) FOR ANY INDIRECT, EXEMPLARY, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES; (C) FOR ANY MATTER BEYOND Mlytics&apos;S REASONABLE CONTROL; OR (D) FOR ANY AMOUNTS THAT, TOGETHER WITH AMOUNTS ASSOCIATED WITH ALL OTHER CLAIMS, EXCEED THE FEES PAID BY Client TO Mlytics FOR THE SERVICES UNDER THIS AGREEMENT IN THE 12 MONTHS PRIOR TO THE ACT THAT GAVE RISE TO THE LIABILITY, IN EACH CASE, WHETHER OR NOT Mlytics HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
          </div>

          <div className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1A1A1A' }}>9. Miscellaneous</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable. This Agreement is not assignable, transferable or sublicensable by Client except with Mlytics&apos;s prior written consent. Mlytics may transfer and assign any of its rights and obligations under this Agreement without consent. This Agreement is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement, and that all waivers and modifications must be in a writing signed by both parties, except as otherwise provided herein. No agency, partnership, joint venture, or employment is created as a result of this Agreement and Client does not have any authority of any kind to bind Mlytics in any respect whatsoever. In any action or proceeding to enforce rights under this Agreement, the prevailing party will be entitled to recover costs and attorneys&apos; fees. All notices under this Agreement will be in writing and will be deemed to have been duly given when received, if personally delivered; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; the day after it is sent, if sent for next day delivery by recognized overnight delivery service; and upon receipt, if sent by certified or registered mail, return receipt requested. This Agreement shall be governed by the laws of the Hong Kong without regard to its conflict of laws provisions.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>The parties shall work together in good faith to issue at least one mutually agreed upon press release within 90 days of the Effective Date, and Client otherwise agrees to reasonably cooperate with Mlytics to serve as a reference account upon request.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>Mlytics may give notice by either (a) means of a general notice on the Service; (b) by electronic mail to Client&apos;s e-mail address on record in Mlytics&apos; account information; or (c) by written communication sent by first class mail to Client&apos;s address on record. Notices will be deemed given 48 hours after mailing or posting (if sent by first class mail or prepaid post) or 12 hours after sending (if sent by email). Client may give notice to Mlytics (such notice will be deemed given when received by Mlytics) by letter sent to Mlytics at the address listed above, attention: CFO, or electronic mail to contact@Mlytics.com. No joint venture, partnership, employment, or agency relationship exists between Client and Mlytics as a result of this Agreement or use of the Service.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>The failure of Mlytics to enforce any right or provision in this Agreement will not constitute a waiver of such right or provision unless in writing.</p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: '#4A4A4A' }}>All Client purchase orders under this Agreement will be subject only to this Agreement. In the event the terms of any such purchase order or similar document conflict with or are additional to this Agreement, this Agreement alone shall apply and shall govern regardless of execution of such document by one or both parties, and Mlytics hereby notifies Client (and, if applicable, the reseller placing an order with Mlytics on Client&apos;s behalf) of Mlytics&apos; objection to and rejection of such conflicting or additional terms. Furthermore, unless otherwise expressly agreed to in writing by Mlytics, no usage of trade, course of dealings, course of performance, understanding, or any term or condition in any purchase order or other document furnished by Client (or a reseller on Client&apos;s behalf) that in any way modifies, is inconsistent with, is different from, attempts to explain and/or is in addition to this Agreement shall be part of this Agreement, and shall be regarded as null and void and is hereby expressly rejected. Additionally, Mlytics failure to object to any term or condition in any oral or written communication from Client (or Client&apos;s reseller), will not constitute an acceptance thereof or a waiver of any term or condition contained in this Agreement. Without limiting the generality of the foregoing, if the express terms of an Order Form conflict with this Agreement, the terms on the Order Form will prevail, but only with respect to that Order Form. Except as otherwise expressly set forth above, all modifications or amendments to this Agreement must be in writing and signed by both parties, except that subsequent Service renewals can be procured by payment (by either Client or Client&apos;s reseller, as applicable) against an issued invoice.</p>
            <p className="text-sm leading-relaxed" style={{ color: '#4A4A4A' }}>No presumption will operate in favor of or against any party as a result of its role in drafting this Agreement.</p>
          </div>

        </div>
      </section>
    </>
  )
}
